# Generated by Django 5.1.7 on 2025-03-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(),
        ),
    ]
